# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
            - nom : Cache
  utilisations : actions/cache@v4.2.3
  avec:
    # Une liste de fichiers, de répertoires et de modèles génériques à mettre en cache et à restaurer
    chemin:
    # Une clé explicite pour restaurer et sauvegarder le cache
    clé:
    # Une chaîne multiligne ordonnée listant les clés correspondant au préfixe, utilisées pour restaurer le cache obsolète si aucune correspondance n'a été trouvée pour la clé. Notez que `cache-hit` renvoie false dans ce cas.
    restore-keys : # facultatif
    # La taille du bloc utilisé pour diviser les fichiers volumineux lors du téléchargement, en octets
    upload-chunk-size : # facultatif
    # Un booléen facultatif lorsqu'il est activé, permet aux exécuteurs Windows d'enregistrer ou de restaurer des caches qui peuvent être restaurés ou enregistrés respectivement sur d'autres plates-formes
    enableCrossOsArchive : # facultatif, la valeur par défaut est false
    # Échec du flux de travail si l'entrée du cache n'est pas trouvée
    fail-on-cache-miss : # facultatif, la valeur par défaut est false
    # Vérifier si une entrée de cache existe pour les entrées données (clé, clés de restauration) sans télécharger le cache
    recherche uniquement : # facultatif, la valeur par défaut est false
    # Exécutez l'étape de publication pour enregistrer le cache même si une autre étape avant échoue
    save-always : # facultatif, la valeur par défaut est false
          
